%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.10-3-g2ea3210 on {{2014,8,3},{15,57,11}}

-ifndef(builtin_pb).
-define(builtin_pb, true).

-define(builtin_pb_gpb_version, "3.10-3-g2ea3210").

-record('PING_OUT',
        {str                            % = 1, string (optional)
        }).

-record('PING_IN',
        {str                            % = 1, string (optional)
        }).

-endif.
